---

In [19]:
import os
import pandas as pd
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split

Found 60600 validated image filenames.
Found 15150 validated image filenames.

In [23]:


def create_model(input_shape, num_categories, num_dishes):
    inputs = Input(shape=input_shape)


    x = Conv2D(32, (3, 3), activation='relu', padding='same')(inputs)
    x = MaxPooling2D((2, 2))(x)
    x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
    x = MaxPooling2D((2, 2))(x)
    x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
    x = MaxPooling2D((2, 2))(x)
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)


    food_category_output = Dense(num_categories, activation='softmax', name='food_category')(x)
    

    dish_output = Dense(num_dishes, activation='softmax', name='dish')(x)


    model = Model(inputs=inputs, outputs=[food_category_output, dish_output])

    return model


input_shape = (128, 128, 3)  
num_categories = 3  
num_dishes = 101  


model = create_model(input_shape, num_categories, num_dishes)


model.compile(optimizer='adam',
              loss={'food_category': 'sparse_categorical_crossentropy', 'dish': 'sparse_categorical_crossentropy'},
              metrics=['accuracy'])


model.summary()

Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_2 (InputLayer)        [(None, 128, 128, 3)]        0         []

 conv2d_18 (Conv2D)          (None, 128, 128, 32)         896       ['input_2[0][0]']

 max_pooling2d_18 (MaxPooli  (None, 64, 64, 32)           0         ['conv2d_18[0][0]']
 ng2D)

 conv2d_19 (Conv2D)          (None, 64, 64, 64)           18496     ['max_pooling2d_18[0][0]']

 max_pooling2d_19 (MaxPooli  (None, 32, 32, 64)           0         ['conv2d_19[0][0]']
 ng2D)

 conv2d_20 (Conv2D)          (None, 32, 32, 128)          73856     ['max_pooling2d_19[0][0]']

 max_pooling2d_20 (MaxPooli  (None, 16, 16, 128)          0         ['conv2d_20[0][0]']
 ng2D)

 flatten_7 (Flatten)         (None, 32768)                0         ['max_pooling2d_20[0][0]']

 dense_10 (Dense)            (None, 512)                  1677772   ['flatten_7[0][0]']
                                                          8

 dropout_7 (Dropout)         (None, 512)                  0         ['dense_10[0][0]']

 food_category (Dense)       (None, 3)                    1539      ['dropout_7[0][0]']

 dish (Dense)                (None, 101)                  51813     ['dropout_7[0][0]']

==================================================================================================
Total params: 16924328 (64.56 MB)
Trainable params: 16924328 (64.56 MB)
Non-trainable params: 0 (0.00 Byte)
__________________________________________________________________________________________________

In [24]:

data = pd.read_csv('train.csv')

train_df, valid_df = train_test_split(data, test_size=0.2, random_state=42)


train_datagen = ImageDataGenerator(
    rescale=1./255,   
    rotation_range=20,  
    width_shift_range=0.2,  
    height_shift_range=0.2,  
    shear_range=0.2,   
    zoom_range=0.2,   
    horizontal_flip=True,  
    fill_mode='nearest' 
)


valid_datagen = ImageDataGenerator(rescale=1./255)


train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    directory='./',  
    x_col='path',
    y_col=['food_category', 'dish'],
    target_size=(128, 128),  
    batch_size=32,
    class_mode='multi_output',
    shuffle=True
)


valid_generator = valid_datagen.flow_from_dataframe(
    dataframe=valid_df,
    directory='./',
    x_col='path',
    y_col=['food_category', 'dish'],
    target_size=(128, 128),
    batch_size=32,
    class_mode='multi_output',
    shuffle=True
)


history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.n // train_generator.batch_size,
    epochs=10, 
    validation_data=valid_generator,
    validation_steps=valid_generator.n // valid_generator.batch_size
)

Found 60600 validated image filenames.
Found 15150 validated image filenames.
Epoch 1/10
1893/1893 [==============================] - 1257s 662ms/step - loss: 5.0552 - food_category_loss: 0.6376 - dish_loss: 4.4176 - food_category_accuracy: 0.7462 - dish_accuracy: 0.0362 - val_loss: 4.6958 - val_food_category_loss: 0.5880 - val_dish_loss: 4.1078 - val_food_category_accuracy: 0.7513 - val_dish_accuracy: 0.0796
Epoch 2/10
1893/1893 [==============================] - 1134s 598ms/step - loss: 4.6810 - food_category_loss: 0.5727 - dish_loss: 4.1083 - food_category_accuracy: 0.7620 - dish_accuracy: 0.0750 - val_loss: 4.4535 - val_food_category_loss: 0.5646 - val_dish_loss: 3.8889 - val_food_category_accuracy: 0.7656 - val_dish_accuracy: 0.1083
Epoch 3/10
1893/1893 [==============================] - 1168s 617ms/step - loss: 4.4843 - food_category_loss: 0.5465 - dish_loss: 3.9378 - food_category_accuracy: 0.7695 - dish_accuracy: 0.1004 - val_loss: 4.3411 - val_food_category_loss: 0.5208 - val_dish_loss: 3.8203 - val_food_category_accuracy: 0.7799 - val_dish_accuracy: 0.1166
Epoch 4/10
1893/1893 [==============================] - 1232s 651ms/step - loss: 4.3551 - food_category_loss: 0.5291 - dish_loss: 3.8259 - food_category_accuracy: 0.7762 - dish_accuracy: 0.1159 - val_loss: 4.0939 - val_food_category_loss: 0.5074 - val_dish_loss: 3.5865 - val_food_category_accuracy: 0.7894 - val_dish_accuracy: 0.1602
Epoch 5/10
1893/1893 [==============================] - 1209s 639ms/step - loss: 4.2558 - food_category_loss: 0.5148 - dish_loss: 3.7410 - food_category_accuracy: 0.7832 - dish_accuracy: 0.1305 - val_loss: 4.0589 - val_food_category_loss: 0.4858 - val_dish_loss: 3.5731 - val_food_category_accuracy: 0.7941 - val_dish_accuracy: 0.1573
Epoch 6/10
1893/1893 [==============================] - 1191s 629ms/step - loss: 4.1776 - food_category_loss: 0.5048 - dish_loss: 3.6728 - food_category_accuracy: 0.7868 - dish_accuracy: 0.1440 - val_loss: 4.0671 - val_food_category_loss: 0.5101 - val_dish_loss: 3.5570 - val_food_category_accuracy: 0.7905 - val_dish_accuracy: 0.1648
Epoch 7/10
1893/1893 [==============================] - 1281s 677ms/step - loss: 4.1219 - food_category_loss: 0.4994 - dish_loss: 3.6225 - food_category_accuracy: 0.7897 - dish_accuracy: 0.1513 - val_loss: 3.9667 - val_food_category_loss: 0.4809 - val_dish_loss: 3.4857 - val_food_category_accuracy: 0.7959 - val_dish_accuracy: 0.1724
Epoch 8/10
1893/1893 [==============================] - 1155s 610ms/step - loss: 4.0615 - food_category_loss: 0.4920 - dish_loss: 3.5695 - food_category_accuracy: 0.7913 - dish_accuracy: 0.1623 - val_loss: 3.8940 - val_food_category_loss: 0.4872 - val_dish_loss: 3.4067 - val_food_category_accuracy: 0.7883 - val_dish_accuracy: 0.1967
Epoch 9/10
1893/1893 [==============================] - 1225s 647ms/step - loss: 4.0203 - food_category_loss: 0.4872 - dish_loss: 3.5331 - food_category_accuracy: 0.7972 - dish_accuracy: 0.1693 - val_loss: 3.7258 - val_food_category_loss: 0.4611 - val_dish_loss: 3.2648 - val_food_category_accuracy: 0.8036 - val_dish_accuracy: 0.2186
Epoch 10/10
1893/1893 [==============================] - 1114s 588ms/step - loss: 3.9907 - food_category_loss: 0.4828 - dish_loss: 3.5078 - food_category_accuracy: 0.7974 - dish_accuracy: 0.1728 - val_loss: 3.7213 - val_food_category_loss: 0.4599 - val_dish_loss: 3.2613 - val_food_category_accuracy: 0.8043 - val_dish_accuracy: 0.2159

In [25]:
test_df = pd.read_csv('test.csv')


test_datagen = ImageDataGenerator(rescale=1./255)


test_generator = test_datagen.flow_from_dataframe(
    dataframe=test_df,
    directory='./',  
    x_col='path',
    y_col=None,  
    target_size=(128, 128),  
    batch_size=32,  
    class_mode=None,  
    shuffle=False
)


predictions = model.predict(test_generator)


category_predictions = predictions[0]
dish_predictions = predictions[1]


category_labels = category_predictions.argmax(axis=1)
dish_labels = dish_predictions.argmax(axis=1)


test_df['predicted_category'] = category_labels
test_df['predicted_dish'] = dish_labels

Found 25250 validated image filenames.
790/790 [==============================] - 116s 145ms/step

In [26]:
test_df

                                  path  predicted_category  predicted_dish
0      images/caprese_salad/820512.jpg                   2              42
1         images/hamburger/2062556.jpg                   2              95
2           images/lasagna/2381454.jpg                   2              25
3              images/ceviche/1995.jpg                   2              42
4            images/poutine/892377.jpg                   2              27
...                                ...                 ...             ...
25245       images/ravioli/2087725.jpg                   2               9
25246      images/ice_cream/504131.jpg                   2              79
25247       images/cannoli/1187751.jpg                   2              15
25248       images/pancakes/477236.jpg                   2              40
25249  images/seaweed_salad/954189.jpg                   0              11

[25250 rows x 3 columns]

In [28]:
import pandas as pd

test_df['classes'] = test_df['predicted_category'].astype(str) + ' ' + test_df['predicted_dish'].astype(str)

df_result = test_df[['path', 'classes']]

In [29]:
df_result

                                  path classes
0      images/caprese_salad/820512.jpg    2 42
1         images/hamburger/2062556.jpg    2 95
2           images/lasagna/2381454.jpg    2 25
3              images/ceviche/1995.jpg    2 42
4            images/poutine/892377.jpg    2 27
...                                ...     ...
25245       images/ravioli/2087725.jpg     2 9
25246      images/ice_cream/504131.jpg    2 79
25247       images/cannoli/1187751.jpg    2 15
25248       images/pancakes/477236.jpg    2 40
25249  images/seaweed_salad/954189.jpg    0 11

[25250 rows x 2 columns]

In [31]:
df_result.to_csv("predictions.csv", index=False)

In [33]:
model.save('mi_modelo.keras')